### ISSUE TITLE
Should this be archived?

### ISSUE THREAD

**Issue by arichiv** [freelawproject/court-listener-api-definition#4]
I noticed it hasn't been updated since 2013

**Comment by kinlane** [comment]
I'd like to see it updated. Can we leave open for a while, and if someone on the team doesn't have time to do, I will do it. Update to at least OpenAPI 2.0 if not 3.0.

**Comment by arichiv** [comment]
I'd be down to do it! Can you tell me how? I'd love to automate it with Travis CI :-) @kinlane
